services:
  - type: web
    name: linkedin-generator
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
